### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by sergei3000** [Tbruno25/pytest-timestamps#2]
Hi the project's pypi [page](https://pypi.org/project/pytest-timestamps/) tells the latest Python version this project works with is 3.10. Could you add support for Python 3.11 too please?

**Comment by Tbruno25** [comment]
Sorry about the delay! 

I'd like to get some basic verification setup for 3.11 in CI before publishing but should have this done soon.

**Comment by sergei3000** [comment]
Sounds great, thanks for responding!

**Comment by Tbruno25** [comment]
Published a new version after confirming compatibility with 3.11 :rocket:
